import item_proto_classes

ITEM_SOCKET_REMAIN_SEC = 0

ITEM_NAME_MAX_LEN = 50
ITEM_NAME_MAX_LEN = 24
ITEM_VALUES_MAX_NUM = 6
ITEM_LIMIT_MAX_NUM = 2
ITEM_APPLY_MAX_NUM = 3
ITEM_SOCKET_MAX_NUM = 6
ITEM_ATTRIBUTE_MAX_NUM = 7
ITEM_ATTRIBUTE_MAX_LEVEL = 5
REFINE_MATERIAL_MAX_NUM = 5
ITEM_ELK_VNUM = 50026

ITEM_VALUE_CHARGING_AMOUNT_IDX = 0
ITEM_SOCKET_CHARGING_AMOUNT_IDX = 2

ITEM_SOCKET_UNIQUE_SAVE_TIME = ITEM_SOCKET_MAX_NUM - 2
ITEM_SOCKET_UNIQUE_REMAIN_TIME = ITEM_SOCKET_MAX_NUM - 1

TYPE = item_proto_classes.Type()
SUBTYPE = item_proto_classes.SubType()
